theme = "solarized_dark"

[editor]
true-color = true
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

# これがないと日本語がインライン入力できないので入れている
[editor.cursor-shape]
insert = "bar"
